### ISSUE TITLE
prepared query and queryRow

### ISSUE THREAD

**Issue by bubnenkoff** [Abscissa/mysql-native-experimental#2]
I am trying to do next:
```
		Prepared prepared = prepare(connection, `SELECT id, login, password, group from 'users' WHERE login=?`);
		prepared.setArgs(login);
		ResultRange result = prepared.queryRow();
```

But I am getting error message that ResultRange is not callable with `queryRow` constructor. Only acceptable is `query`

What `PreparedImpl` is different from simple `Prepared`? I tried it, but got message that it's can't be called because annotate as `disabled`

**Comment by Abscissa** [comment]
As in the API reference (<http://semitwist.com/mysql-native-docs/v0.2.0-preview1/mysql/protocol/prepared/PreparedImpl.queryRow.html>) queryRow returns Nullable!Row, not ResultRange. [query](http://semitwist.com/mysql-native-docs/v0.2.0-preview1/mysql/protocol/prepared/PreparedImpl.query.html) returns ResultRange.

PreparedImpl is internal implementation of Prepared, not to be used directly because Prepared wraps PreparedImpl with reference counting. (Need to document "PreparedImpl vs Prepared" better. I really wish ddox would include the alias this'd members of Prepared so I could omit PreparedImpl from the docs)
